### PR TITLE
Updated to include bookmarklet for HTML Preview!

### PR DESCRIPTION
**Pull request by landonreed**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Pls pay attention to
```
Content-Security-Policy: default-src *; script-src assets-cdn.github.com collector-cdn.github.com; object-src assets-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' assets-cdn.github.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com; media-src 'none'; frame-src 'self' render.githubusercontent.com gist.github.com www.youtube.com player.vimeo.com checkout.paypal.com; font-src assets-cdn.github.com; connect-src 'self' live.github.com wss://live.github.com uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com; base-uri 'self'; form-action 'self' github.com
```

**Comment by niutech** [comment]
@szepeviktor IT works fine in Firefox 40. What is the URL and your browser?

**Comment by szepeviktor** [comment]
I use the Developer Edition: v42

**Comment by szepeviktor** [comment]
`script-src assets-cdn.github.com collector-cdn.github.com` is the interesting part.

**Comment by niutech** [comment]
Thanks. Could you provide a test case URL?

**Comment by szepeviktor** [comment]
This PR is about a bookmarklet.
Bookmark this, use the browser above:
```
javascript:void(document.location='http://htmlpreview.github.io/?'+String(document.location));
```
And you get this on the browser console:
```
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com https://collector-cdn.github.com").
```

**Comment by landonreed** [comment]
@szepeviktor could you clarify what site you're trying to use the bookmarklet on?  It may not work on GitHub.com, for example, but if you go to some other site (e.g., https://www.google.com/?gws_rd=ssl#q=test) it works just fine.

**Comment by szepeviktor** [comment]
Yes, only sites with strict CSP prevent running local JS.

**Comment by niutech** [comment]
I think this is a well known [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=866522). Sorry, but I cannot do much with it.

**Comment by landonreed** [comment]
Closing, this is stale.

**Pull request closed without merging**
